server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${rendom.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZond: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.
